### ISSUE TITLE
I get always the error with liblttng-ust.so.0

### ISSUE THREAD

**Issue by BuriKizilkaya** [jeremy-prater/meta-dotnet#12]
Problem: conflicting requests
  - nothing provides liblttng-ust.so.0()(64bit) needed by dotnet-hello-world-1.0-r0.core2_64

**Comment by jeremy-prater** [comment]
What host OS are you using to build?

**Comment by BuriKizilkaya** [comment]
I use a WSL Setup with Docker (Debian GNU/Linux 12 (bookworm))

**Comment by BuriKizilkaya** [comment]
I want built the application with self-contained but with no single file...

**Comment by angelo-zehnder** [comment]
This is not related to meta-dotnet, but the fact you don't have that library installed in your OS. please install it.

**Comment by jeremy-prater** [comment]
Closing per comments from @angelo-zehnder
